apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstdeployment
  labels:
    app: myflaskapp
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: myflaskapp
    spec:
      containers:
        - name: myfirstpod
          image: psrv3/argocd-example:v1.0
          ports:
            - containerPort: 5000
  replicas: 3
  selector:
    matchLabels:
      app: myflaskapp
---
apiVersion: v1
kind: Service
metadata:
  name: myfirstpodsvc
spec:
  selector:
    app: myflaskapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort